version: '3.7'

services:
  mysql:
    image: mysql:8.0
    restart: always
    entrypoint: [
      '/entrypoint.sh',
      '--default-authentication-plugin=mysql_native_password',
      '--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    ]
    environment:
      MYSQL_DATABASE: 'database_name'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

#  mongo:
#    image: mongo:4.2.19
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "example"
#    ports:
#      - '27017:27017'
#    expose:
#      - '27017'
#    volumes:
#      - mongo_data:/data/db

volumes:
  mysql_data:
    name: mysql_data
#  mongo_data:
#    name: mongo_data
